# AI News Bot 配置文件示例
# 复制此文件为 news.yml 并填入实际配置

# 飞书机器人配置 (支持多个群组推送)
lark:
  # 主要群组
  primary:
    api_url: "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_WEBHOOK_ID"
    api_secret: "YOUR_WEBHOOK_SECRET"
    name: "主群组"
  
  # 第二个群组（可选）
  secondary:
    api_url: "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_SECOND_WEBHOOK_ID"
    api_secret: "YOUR_SECOND_WEBHOOK_SECRET"
    name: "备用群组"
  
  # 可以继续添加更多群组...

# API 配置
apis:
  # AutoAgents AI 配置
  autoagentsai:
    # 统一AI处理 Agent (JSON格式翻译+总结)
    ai_agent:
      agent_id: "YOUR_AGENT_ID"
      personal_auth_key: "YOUR_PERSONAL_AUTH_KEY"
      personal_auth_secret: "YOUR_PERSONAL_AUTH_SECRET"

# Supabase 数据库配置
supabase:
  url: "https://your-project.supabase.co"
  anon_key: "YOUR_SUPABASE_ANON_KEY"

# 数据库表配置
database:
  table_name: "ai_news"

# 配置说明:
# 1. lark: 飞书群机器人配置，可以配置多个群组
#    - 获取方式: 在飞书群中添加自定义机器人，获取 webhook URL 和签名密钥
# 
# 2. autoagentsai: AutoAgents AI服务配置
#    - 获取方式: 访问 https://autoagents.ai 注册并创建 Agent
# 
# 3. supabase: Supabase数据库配置（用于存储新闻）
#    - 获取方式: 访问 https://supabase.com 创建项目
#    - 需要创建表: ai_news (参考 database.py 中的表结构)



