# Docker Compose 配置 - 定时任务调度器
# 使用方法: docker-compose -f docker/docker-compose.scheduler.yml up -d

name: agent2im-scheduler

services:
  scheduler:
    build:
      context: ../
      dockerfile: docker/Dockerfile.scheduler
    container_name: agent2im-scheduler
    environment:
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    volumes:
      # 挂载配置文件（必需）
      - ../backend/config/scheduled_tasks.json:/app/backend/config/scheduled_tasks.json:ro
      - ../backend/config/labor_hour.json:/app/backend/config/labor_hour.json:ro
      - ../backend/config/news.json:/app/backend/config/news.json:ro
      - ../backend/config/people.json:/app/backend/config/people.json:ro
      - ../backend/config/task.json:/app/backend/config/task.json:ro
      - ../backend/config/message.json:/app/backend/config/message.json:ro
      # 挂载日志目录（可选，方便查看日志）
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - scheduler-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "start_unified_scheduler.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  scheduler-network:
    driver: bridge



